---
language: python
sudo: required
python:
  - "3.5"

cache:
  - datasets/cifar-10-batches-py

install:
  - sudo apt-get -yqq install time
  - pip install -r requirements.txt
  - ./datasets/get_datasets.sh

script:
  - /usr/bin/env time --verbose nosetests
