---
language: python
python:
  - "3.5"

cache:
  - pip
  - directories:
    - datasets

install:
  - pip install -r requirements.txt
  - ./datasets/get_datasets.sh

script:
  - nosetests --show-skipped
